import "../styles/globals.scss";
import { Inter } from "next/font/google";
import { ReduxProvider } from "@/redux/provider";
import { NextAuthProvider } from "@/providers/NextAuthProviders";

const inter = Inter({ subsets: ["latin"] });

// Only supported in server components
export const metadata = {
  title: {
    default: "Shop and Pay",
    template: "%s | Shop and Pay",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <NextAuthProvider>
          <ReduxProvider>{children}</ReduxProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
