"use client";

import "../styles/globals.scss";
import { Inter } from "next/font/google";
import { ReduxProvider } from "@/redux/provider";
import { NextAuthProvider } from "@/providers/NextAuthProviders";
import { PayPalScriptProvider } from "@paypal/react-paypal-js";
import { getPaypalKeys } from "@/utils/tokens";

const inter = Inter({ subsets: ["latin"] });

// Only supported in server components
// export const metadata = {
//   title: {
//     default: "Shop and Pay",
//     template: "%s | Shop and Pay",
//   },
//   description: "Generated by create next app",
// };

const payPalInitialOptions = {
  clientId: getPaypalKeys().id,
  currency: "USD",
  intent: "capture",
};

export default function RootLayout({ children }) {
  console.log("root component");
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <NextAuthProvider>
          <ReduxProvider>
            <PayPalScriptProvider options={payPalInitialOptions}>
              {children}
            </PayPalScriptProvider>
          </ReduxProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
